### ISSUE TITLE
syntax error 

### ISSUE THREAD

**Issue by ezspot** [NotoriousPyro/SQLite-to-MariaDB-MySQL-perl-script#1]
root@ubuntu:/home/ts3/teamspeak3-server_linux_amd64# ./sqlite-to-mariadb.pl export.sqlite > export.mariadb
./sqlite-to-mariadb.pl: line 7: syntax error near unexpected token `newline'
./sqlite-to-mariadb.pl: line 7: `<!DOCTYPE html>'

**Comment by NotoriousPyro** [comment]
You're running the file incorrectly. You need to tell it to run the file in perl:

`perl sqlite-to-mariadb.pl [INPUT FILE] > [OUTPUT FILE]`

The way you're running it is:
`./sqlite-to-mariadb.pl [INPUT FILE] > [OUTPUT FILE]`

Try the latest version of the file which I just amended. Also, try saving the file in Unix (LF) format as opposed to Windows (CR LF).
